FROM rocker/r-base:latest

RUN mkdir cat-api

# Create and change to this directory
WORKDIR cat-api

# Set environment variable so apt-get runs without interactive dialogue
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libmariadb-dev \
    r-cran-dplyr \
    r-cran-readr \
    r-cran-jsonlite \
    r-cran-dbi \
    r-cran-xml2 \
    r-cran-tidyr \
    r-cran-dbplyr \
    r-cran-purrr \
    r-cran-rmysql

# Copy scripts
COPY "xml_to_json.R" "/cat-api/xml_to_json.R"
COPY "translate_rs.R" "/cat-api/translate_rs.R"
COPY "launch.sh" "/cat-api/launch.sh"

# Label volumes to be mounted
VOLUME /cat-api/inputs

# Make a runspec
CMD [ "./launch.sh" ]